# Generated by Django 5.1.3 on 2024-11-22 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='product_module.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_expire',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
    ]
