# Generated by Django 5.1.3 on 2024-11-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pin_top',
            field=models.BooleanField(default=False, verbose_name='پین کردن محصول'),
        ),
    ]
