# Generated by Django 5.1.3 on 2024-11-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='', upload_to='blog/images', verbose_name='عکس مقاله'),
            preserve_default=False,
        ),
    ]
