# Generated by Django 5.1.3 on 2024-11-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_alter_blog_options_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(help_text='قیمت ها به تومان است', verbose_name='قیمت'),
        ),
    ]
