# Generated by Django 5.1.3 on 2024-11-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_product_short_description_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='نشانی محصول'),
        ),
    ]
