# Generated by Django 5.1.3 on 2024-11-28 13:33

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف')),
                ('discount_expire', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای تخفیف')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_expire',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='درصورتی که برای محصول تخفیفی در نظر ندارید این بخش را نادیده بگیرید', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product_module.discount'),
        ),
    ]
