# Generated by Django 5.1.3 on 2024-11-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0014_alter_discount_options_alter_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url_title',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='نشانی دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='نشانی محصول'),
        ),
    ]
