# Generated by Django 5.1.3 on 2024-11-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0015_remove_category_url_title_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, unique=True, verbose_name='نشانی دسته بندی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=2, unique=True, verbose_name='نشانی محصول'),
            preserve_default=False,
        ),
    ]
