# Generated by Django 5.1.3 on 2024-11-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0016_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='product_module.category'),
        ),
    ]
