# Generated by Django 5.1.3 on 2024-12-04 20:23

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0017_remove_product_category_product_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_expire',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ انقضای تخفیف'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='کامنت')),
                ('read_by_admin', models.BooleanField(default=False, verbose_name='خوانده شده توسط ادمین')),
                ('visibel', models.BooleanField(default=False, verbose_name='نمایش داده شود / نشود')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product_module.blog', verbose_name='مقاله')),
                ('parent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='product_module.comment', verbose_name='کامنت پدر')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product_module.product', verbose_name='محصول')),
            ],
        ),
    ]
