# Generated by Django 5.1.3 on 2024-12-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_module', '0004_remove_cart_items_cart_products_delete_itemcart'),
        ('product_module', '0020_discount_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='product_module.product', verbose_name='محصولات'),
        ),
    ]
