# Generated by Django 5.1.3 on 2024-12-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_module', '0005_alter_cart_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
