# Generated by Django 5.1.3 on 2024-11-24 12:57

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='آدرس')),
                ('image', models.ImageField(upload_to='ad/banner', verbose_name='بنر')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expire_date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ انقضا')),
            ],
        ),
    ]
