# Generated by Django 5.1.3 on 2024-11-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'تبلیغ', 'verbose_name_plural': 'تبلیغات'},
        ),
        migrations.AddField(
            model_name='ad',
            name='visibel',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
