# Generated by Django 5.1.3 on 2024-11-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_alter_ad_options_ad_visibel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='ad',
            name='visibel',
            field=models.BooleanField(default=False, verbose_name='نمایش داده شود /نشود'),
        ),
    ]
