# Generated by Django 5.1.3 on 2024-11-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_remove_ad_created_at_alter_ad_visibel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان'),
        ),
    ]
